name: build-custom-silverblue
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '5 3 * * *'  # 3am-ish UTC everyday (timed against official fedora container pushes)
  workflow_dispatch:

jobs:
  build-custom-silverblue:
    uses: ./.github/workflows/reusable-build.yaml
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    with:
      containerfile_path: ./Containerfile
      registry: ghcr.io
      namespace: samhclark
      image_name: custom-silverblue
      tags: |
        42
    secrets:
      cosign_password: ${{ secrets.COSIGN_PASSWORD }}
      cosign_private_key: ${{ secrets.COSIGN_PRIVATE_KEY }}
